require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NegotiatorsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Negotiator. As you add validations to Negotiator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { username: Faker::Internet.user_name }
  }

  let(:invalid_attributes) {
    { username: [-250,3,1] }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NegotiatorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all negotiators as @negotiators" do
      negotiator = Negotiator.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:negotiators)).to eq([negotiator])
    end
  end

  describe "GET #show" do
    it "assigns the requested negotiator as @negotiator" do
      negotiator = Negotiator.create! valid_attributes
      get :show, {:id => negotiator.to_param}, valid_session
      expect(assigns(:negotiator)).to eq(negotiator)
    end
  end

  describe "GET #new" do
    it "assigns a new negotiator as @negotiator" do
      get :new, {}, valid_session
      expect(assigns(:negotiator)).to be_a_new(Negotiator)
    end
  end

  describe "GET #edit" do
    it "assigns the requested negotiator as @negotiator" do
      negotiator = Negotiator.create! valid_attributes
      get :edit, {:id => negotiator.to_param}, valid_session
      expect(assigns(:negotiator)).to eq(negotiator)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Negotiator" do
        expect {
          post :create, {:negotiator => valid_attributes}, valid_session
        }.to change(Negotiator, :count).by(1)
      end

      it "assigns a newly created negotiator as @negotiator" do
        post :create, {:negotiator => valid_attributes}, valid_session
        expect(assigns(:negotiator)).to be_a(Negotiator)
        expect(assigns(:negotiator)).to be_persisted
      end

      it "redirects to the created negotiator" do
        post :create, {:negotiator => valid_attributes}, valid_session
        expect(response).to redirect_to(Negotiator.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved negotiator as @negotiator" do
        post :create, {:negotiator => invalid_attributes}, valid_session
        expect(assigns(:negotiator)).to be_a_new(Negotiator)
      end

      it "re-renders the 'new' template" do
        post :create, {:negotiator => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { username: "updated_username" }
      }

      it "updates the requested negotiator" do
        negotiator = Negotiator.create! valid_attributes
        put :update, {:id => negotiator.to_param, :negotiator => new_attributes}, valid_session
        negotiator.reload
        expect(negotiator.username).to eq "updated_username"
      end

      it "assigns the requested negotiator as @negotiator" do
        negotiator = Negotiator.create! valid_attributes
        put :update, {:id => negotiator.to_param, :negotiator => valid_attributes}, valid_session
        expect(assigns(:negotiator)).to eq(negotiator)
      end

      it "redirects to the negotiator" do
        negotiator = Negotiator.create! valid_attributes
        put :update, {:id => negotiator.to_param, :negotiator => valid_attributes}, valid_session
        expect(response).to redirect_to(negotiator)
      end
    end

    context "with invalid params" do
      it "assigns the negotiator as @negotiator" do
        negotiator = Negotiator.create! valid_attributes
        put :update, {:id => negotiator.to_param, :negotiator => invalid_attributes}, valid_session
        expect(assigns(:negotiator)).to eq(negotiator)
      end

      it "re-renders the 'edit' template" do
        negotiator = Negotiator.create! valid_attributes
        put :update, {:id => negotiator.to_param, :negotiator => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested negotiator" do
      negotiator = Negotiator.create! valid_attributes
      expect {
        delete :destroy, {:id => negotiator.to_param}, valid_session
      }.to change(Negotiator, :count).by(-1)
    end

    it "redirects to the negotiators list" do
      negotiator = Negotiator.create! valid_attributes
      delete :destroy, {:id => negotiator.to_param}, valid_session
      expect(response).to redirect_to(negotiators_url)
    end
  end

end
